on:
  workflow_dispatch:
    inputs:
      cache-ref-key:
        type: string
        description: cache-ref-key to upload to release page
        required: true
      release-id:
        type: string
        description: release id destination
        required: true

name: Upload cache to release page
jobs:
  upload:
    name: Upload release-artifacts
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      packages: write
      checks: write
      contents: write
      statuses: read
    steps:
    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          *.tar.gz
          *.asc
          *.deb
          *.rpm
          checksums.txt
        key: ${{ github.event.inputs.cache-ref-key }}
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ github.event.inputs.release-id }}
        args: '*.tar.gz *.asc *.deb *.rpm checksums.txt'
